(function(){var St=window.St,$=St.$,f=St.fmt,S=St.S,pg=document.body.dataset.page;
function card(p){var o=St.off(p);return '<article class="k"><a class="pic" href="product.html?id='+p.id+'" style="--t:'+p.tone+'">'+(o?'<i class="sale">'+o+'% off</i>':'')+p.cat+'</a><h3><a href="product.html?id='+p.id+'">'+p.name+'</a></h3><p class="s">'+p.sub+'</p><p class="p">'+(p.old?'<s>'+f(p.old)+'</s>':'')+f(p.price)+'</p><button class="add" data-add="'+p.id+'">Add to bag</button></article>'}
function lines(){var L=St.lines();return L.length?L.map(function(l){return '<div class="ln"><div class="sq2" style="--t:'+l.p.tone+'"></div><div><h4>'+l.p.name+'</h4><div class="qt"><button data-dec="'+l.p.id+'">-</button>'+l.q+'<button data-inc="'+l.p.id+'">+</button><button class="rm" data-rm="'+l.p.id+'">Remove</button></div></div><b>'+f(l.t)+'</b></div>'}).join(''):'<p style="text-align:center;padding:30px 0">Your bag is empty.</p>'}
function sum(){var t=St.totals();return '<div class="tt" style="margin-top:16px"><div><span>Subtotal</span><span>'+f(t.sub)+'</span></div>'+(t.d?'<div><span>Bundle / coupon savings</span><span>-'+f(t.d)+'</span></div>':'')+'<div><span>Shipping</span><span>'+(t.sh?f(t.sh):'Free')+'</span></div><div class="g"><span>Total</span><span>'+f(t.total)+'</span></div><div style="margin-top:12px"><input class="cc" placeholder="Coupon code"> <button class="rm cp">Apply</button></div><button class="btn" style="width:100%;margin-top:16px" data-checkout '+(t.n?'':'disabled')+'>Checkout</button></div>'}
function bar(){var t=St.totals(),l=Math.max(0,S.free-(t.sub-t.d));return '<p style="text-align:center;margin:0;font-size:14px">'+(t.sub?(l?'Add '+f(l)+' more for free shipping':'You have free shipping'):'Free shipping above '+f(S.free))+'</p><div class="bar"><i style="width:'+Math.min(100,(t.sub-t.d)/S.free*100)+'%"></i></div>'}
function dr(o){$('#dr').classList.toggle('on',o);$('#ov').classList.toggle('on',o)}
St.opened=function(){if(pg!='cart')dr(true)};
St.onCart=function(){$('#dl').innerHTML=bar()+lines()+sum();if($('#items')){$('#shipbar').innerHTML=bar();$('#items').innerHTML=lines();$('#sum').innerHTML=sum()}};
document.addEventListener('click',function(e){if(e.target.id=='cl'||e.target.id=='ov')dr(false);var b=e.target.closest('#open');if(b&&pg!='cart'){e.preventDefault();dr(true)}if(e.target.classList.contains('cp')){var c=e.target.parentNode.querySelector('.cc');if(St.coupon(c.value))St.onCart();else St.toast('Invalid coupon')}});
if(pg=='home')$('#feat').innerHTML=St.P.map(card).join('');
if(pg=='shop'){var cat=St.qs('cat')||'All',q=(St.qs('q')||'').toLowerCase();function d(){$('#pl').innerHTML=['All'].concat(S.cats).map(function(c){return '<button class="'+(c==cat?'on':'')+'" data-c="'+c+'">'+c+'</button>'}).join('');$('#grid').innerHTML=St.list({cat:cat,q:q}).map(card).join('')}$('#pl').onclick=function(e){if(e.target.dataset.c){cat=e.target.dataset.c;d()}};d()}
if(pg=='product'){var p=St.by(St.qs('id'))||St.P[0],n=1;document.title=p.name+' | '+S.name;
 function pd(){var o=[[1,'Buy 1',0],[2,'Buy 2, save 15%',.15],[3,'Buy 3, save 20%',.2]];
 $('#pdp').innerHTML='<div class="imgs" style="--t:'+p.tone+'"><div class="arch"><span>'+p.cat+'</span></div><div class="sq">Detail image</div></div><div class="inf"><p class="ey">'+p.cat+' care</p><h1>'+p.name+'</h1><div>'+p.sub+'. Rated '+p.rating+' out of 5.</div><div class="pr">'+(p.old?'<s>'+f(p.old)+'</s>':'')+f(p.price)+'</div><div class="bo">'+o.map(function(x){return '<label class="'+(n==x[0]?'on':'')+'"><input type="radio" name="b" value="'+x[0]+'">'+x[1]+'<b>'+f(p.price*x[0]*(1-x[2]))+'</b></label>'}).join('')+'</div><button class="btn" data-add="'+p.id+'" data-q="'+n+'">Add to bag</button><details open><summary>Details</summary><p>'+p.name+'. Placeholder copy: replace with the client description.</p></details><details><summary>How to use</summary><p>Usage steps go here.</p></details><details><summary>Shipping and returns</summary><p>Ships in 2 days. 7 day returns on unused products.</p></details></div>';
 $('.bo').onchange=function(e){n=+e.target.value;pd()}}pd();
 $('#rel').innerHTML=St.P.filter(function(x){return x.id!=p.id}).slice(0,5).map(card).join('')}
})();