(function(){var St=window.St,$=St.$,f=St.fmt,S=St.S,pg=document.body.dataset.page;
function card(p){return '<article class="c"><a class="im" href="product.html?id='+p.id+'" style="--t:'+p.tone+'">'+p.cat+'</a><div class="b"><small>SKU VL-'+(1000+p.id)+'</small><a class="n" href="product.html?id='+p.id+'">'+p.name+'</a><p>'+p.sub+'</p><div class="pr"><b>'+f(p.price)+'</b>'+(p.old?'<s>'+f(p.old)+'</s>':'')+'</div><div class="acts"><button class="bt" data-add="'+p.id+'">Add to cart</button><a class="bt o" href="product.html?id='+p.id+'">Details</a></div></div></article>'}
if(pg=='home')$('#feat').innerHTML=St.P.slice(0,4).map(card).join('');
if(pg=='shop'){var o={cat:St.qs('cat')||'All',q:(St.qs('q')||'').toLowerCase(),r:'',s:''};
 function draw(){var l=St.list(o);$('#cnt').textContent=l.length+' products';$('#grid').innerHTML=l.map(card).join('');
  var b=function(k,v,t){return '<button class="'+(o[k]==v?'on':'')+'" data-k="'+k+'" data-v="'+v+'">'+t+'</button>'};
  $('#side').innerHTML='<div><h4>Category</h4>'+b('cat','All','All products')+S.cats.map(function(c){return b('cat',c,c)}).join('')+'</div><div><h4>Price</h4>'+b('r','','Any price')+b('r','a','Under 500')+b('r','b','500 to 2,000')+b('r','c','Above 2,000')+'</div>'}
 $('#side').onclick=function(e){if(e.target.dataset.k){o[e.target.dataset.k]=e.target.dataset.v;draw()}};$('#so').onchange=function(){o.s=this.value;draw()};draw()}
if(pg=='product'){var p=St.by(St.qs('id'))||St.P[0];$('#bc').textContent=p.name;document.title=p.name+' | '+S.name;
 var T={Overview:'<p>'+p.name+'. '+p.sub+'. Placeholder description: replace with the client product copy.</p>',Specifications:'<table><tr><td>Category</td><td>'+p.cat+'</td></tr><tr><td>Size / pack</td><td>'+p.sub+'</td></tr><tr><td>Standard</td><td>As per client data</td></tr><tr><td>Warranty</td><td>1 year</td></tr></table>',Downloads:'<p>Brochure and datasheet links go here.</p>'};
 $('#pdp').className='pdp';$('#pdp').innerHTML='<div><div class="big" style="--t:'+p.tone+'">'+p.cat+'</div><div class="th" style="--t:'+p.tone+'"><div></div><div></div><div></div></div></div><div><small>SKU VL-'+(1000+p.id)+'</small><h1>'+p.name+'</h1><div>'+p.sub+' &nbsp;|&nbsp; Rated '+p.rating+'/5</div><div class="pr"><b>'+f(p.price)+'</b>'+(p.old?'<s>'+f(p.old)+'</s>':'')+'<div style="font-size:13px;color:#6a7588">Inclusive of GST</div></div><div class="buy"><input id="qn" type="number" min="1" value="1"><button class="bt" data-add="'+p.id+'" data-qin="#qn">Add to cart</button><a class="bt o" href="contact.html">Request quote</a></div><div class="note">Dispatch in 2 working days. Bulk orders: ask for dealer pricing.</div></div><div style="grid-column:1/-1"><div class="tabs">'+Object.keys(T).map(function(k,i){return '<button class="'+(i?'':'on')+'" data-t="'+k+'">'+k+'</button>'}).join('')+'</div><div class="tp" id="tp">'+T.Overview+'</div></div>';
 $('.tabs').onclick=function(e){var k=e.target.dataset.t;if(k){this.querySelectorAll('button').forEach(function(b){b.classList.toggle('on',b==e.target)});$('#tp').innerHTML=T[k]}}}
if(pg=='cart'){St.onCart=function(){var L=St.lines(),t=St.totals();
 $('#items').innerHTML=L.length?'<table class="ct"><tr><th>Product</th><th>Price</th><th>Qty</th><th>Total</th><th></th></tr>'+L.map(function(l){return '<tr><td><a href="product.html?id='+l.p.id+'"><b>'+l.p.name+'</b></a><br><small>'+l.p.sub+'</small></td><td>'+f(l.p.price)+'</td><td><div class="q"><button data-dec="'+l.p.id+'">-</button><span>'+l.q+'</span><button data-inc="'+l.p.id+'">+</button></div></td><td><b>'+f(l.t)+'</b></td><td><button class="q" data-rm="'+l.p.id+'" style="padding:6px 10px;background:#fff;cursor:pointer">Remove</button></td></tr>'}).join('')+'</table>':'<p>Your cart is empty. <a href="shop.html"><u>Browse products</u></a></p>';
 $('#sum').innerHTML='<h3>Summary</h3><div><span>Subtotal</span><span>'+f(t.sub)+'</span></div>'+(t.d?'<div><span>Discount</span><span>-'+f(t.d)+'</span></div>':'')+'<div><span>Shipping</span><span>'+(t.sh?f(t.sh):'Free')+'</span></div><div class="t"><span>Total</span><span>'+f(t.total)+'</span></div><div class="cp" style="margin-top:14px"><input id="cc" placeholder="Coupon: WELCOME10"><button class="bt o" id="ca" style="padding:8px 14px">Apply</button></div><button class="bt" style="width:100%;margin-top:14px" data-checkout '+(t.n?'':'disabled')+'>Place order</button><a class="bt o" style="width:100%;text-align:center;margin-top:8px" href="contact.html">Request quote instead</a>';
 $('#ca').onclick=function(){if(St.coupon($('#cc').value))St.onCart();else St.toast('Invalid coupon')}}}
})();