(function(){var St=window.St,$=St.$,f=St.fmt,S=St.S,pg=document.body.dataset.page;
function box(p){return '<article class="bx"><small>FW-'+(3000+p.id)+'</small><a class="n" href="product.html?id='+p.id+'">'+p.name+'</a><p>'+p.sub+'</p><div class="pp">'+f(p.price)+(p.old?'<s>'+f(p.old)+'</s>':'')+'</div><button class="bt" data-add="'+p.id+'">+ ADD</button></article>'}
function row(p){return '<div class="rw"><span><b>FW-'+(3000+p.id)+'</b></span><a class="n" href="product.html?id='+p.id+'">'+p.name+'</a><span>'+p.sub+'</span><b>'+f(p.price)+(p.old?'<s>'+f(p.old)+'</s>':'')+'</b><button class="bt" data-add="'+p.id+'">+ ADD</button></div>'}
if(pg=='home')$('#feat').innerHTML=St.P.slice(0,4).map(box).join('');
if(pg=='shop'){var cat=St.qs('cat')||'All',q=(St.qs('q')||'').toLowerCase();function d(){$('#fl').innerHTML=['All'].concat(S.cats).map(function(c){return '<button class="'+(c==cat?'on':'')+'" data-c="'+c+'">'+c.toUpperCase()+'</button>'}).join('');var l=St.list({cat:cat,q:q});$('#grid').innerHTML=l.length?l.map(row).join(''):'<div class="rw">NOTHING FOUND.</div>'}$('#fl').onclick=function(e){if(e.target.dataset.c){cat=e.target.dataset.c;d()}};d()}
if(pg=='product'){var p=St.by(St.qs('id'))||St.P[0];document.title=p.name+' | '+S.name;$('#bc').textContent=p.name.toUpperCase();$('#ttl').textContent=p.name;
 $('#pdp').className='pd';$('#pdp').innerHTML='<div class="sheet"><div class="ph" style="--t:'+p.tone+'">PHOTO</div><table><tr><td>SKU</td><td>FW-'+(3000+p.id)+'</td></tr><tr><td>TYPE</td><td>'+p.cat.toUpperCase()+'</td></tr><tr><td>SPEC</td><td>'+p.sub+'</td></tr><tr><td>RATING</td><td>'+p.rating+' / 5</td></tr><tr><td>DISPATCH</td><td>SAME DAY BEFORE 2 PM</td></tr></table><p>Placeholder copy: replace with the client product description.</p></div><div class="bb"><b>PRICE</b><div class="big">'+f(p.price)+(p.old?'<s>'+f(p.old)+'</s>':'')+'</div><b>QTY</b><input id="qn" type="number" min="1" value="1"><button class="bt" data-add="'+p.id+'" data-qin="#qn">ADD TO CART</button><a class="bt w" href="contact.html">TRADE PRICE</a></div>'}
if(pg=='cart'){St.onCart=function(){var L=St.lines(),t=St.totals(),pad=function(s){return s};
 $('#items').innerHTML=L.length?L.map(function(l){return '<div class="li"><span class="n">'+l.p.name+'</span><b>'+f(l.t)+'</b><div class="ctl"><button data-dec="'+l.p.id+'">-</button>X'+l.q+'<button data-inc="'+l.p.id+'">+</button><button class="x" data-rm="'+l.p.id+'">DELETE</button></div><small>'+f(l.p.price)+' EACH</small></div>'}).join(''):'<p class="c">NOTHING HERE. <a href="shop.html"><u>GO SHOPPING</u></a></p>';
 $('#sum').innerHTML='<div class="tt"><div><span>SUBTOTAL</span><span>'+f(t.sub)+'</span></div>'+(t.d?'<div><span>DISCOUNT</span><span>-'+f(t.d)+'</span></div>':'')+'<div><span>SHIPPING</span><span>'+(t.sh?f(t.sh):'FREE')+'</span></div><div class="g"><span>TOTAL</span><span>'+f(t.total)+'</span></div><p style="margin:14px 0 0"><input id="cc" placeholder="COUPON: WELCOME10"> <button class="bt" id="ca" style="padding:9px 14px">APPLY</button></p><button class="bt" data-checkout '+(t.n?'':'disabled')+'>CHECKOUT &rarr;</button></div>';
 $('#ca').onclick=function(){if(St.coupon($('#cc').value))St.onCart();else St.toast('INVALID COUPON')}}}
})();