(function(){var St=window.St,$=St.$,f=St.fmt,S=St.S,pg=document.body.dataset.page,R=['3/4','1/1','4/5','5/6'];
function card(p,i){return '<article class="k"><a class="pic" href="product.html?id='+p.id+'" style="--t:'+p.tone+';aspect-ratio:'+(R[(i||0)%4])+'">'+p.cat+'</a><div class="m"><h3><a href="product.html?id='+p.id+'">'+p.name+'</a></h3><span>'+(p.old?'<s>'+f(p.old)+'</s>':'')+f(p.price)+'</span></div><p class="s">'+p.sub+'</p><button class="ad" data-add="'+p.id+'">Add to bag</button></article>'}
document.addEventListener('click',function(e){if(e.target.id=='mn')$('#menu').classList.add('on');if(e.target.id=='mx'||(e.target.closest('#menu a')))$('#menu').classList.remove('on')});
if(pg=='home'){$('#c1').innerHTML=[0,2,4].map(function(i){var p=St.P[i];return card(p,0)}).join('');$('#c2').innerHTML=[1,3,5].map(function(i){var p=St.P[i];return card(p,2)}).join('')}
if(pg=='shop'){var cat=St.qs('cat')||'All',q=(St.qs('q')||'').toLowerCase();function d(){$('#fl').innerHTML=['All'].concat(S.cats).map(function(c){return '<button class="'+(c==cat?'on':'')+'" data-c="'+c+'">'+c+'</button>'}).join('<span>/</span>');$('#grid').innerHTML=St.list({cat:cat,q:q}).map(card).join('')}$('#fl').onclick=function(e){if(e.target.dataset.c){cat=e.target.dataset.c;d()}};d()}
if(pg=='product'){var p=St.by(St.qs('id'))||St.P[0],n=1;document.title=p.name+' | '+S.name;
 function pd(){$('#pdp').className='sp';$('#pdp').innerHTML='<div class="stick" style="--t:'+p.tone+'">'+p.cat+'</div><div class="pc"><p class="sm">'+p.cat+'</p><h1>'+p.name+'</h1><div class="pr">'+(p.old?'<s>'+f(p.old)+'</s>':'')+f(p.price)+'</div><p>'+p.name+'. Placeholder copy: replace with a short, honest description of the piece and how it is made.</p><ul><li><span>Size</span><span>'+p.sub+'</span></li><li><span>Made</span><span>By hand, small batch</span></li><li><span>Care</span><span>See care card</span></li><li><span>Delivery</span><span>3 to 5 working days</span></li></ul><div class="qr"><button id="m">-</button><span>'+n+'</span><button id="pl">+</button></div><button class="bk" data-add="'+p.id+'" data-q="'+n+'">Add to bag</button><div class="rl">'+St.P.filter(function(x){return x.id!=p.id}).slice(0,2).map(function(x){return card(x,1)}).join('')+'</div></div>';
 $('#m').onclick=function(){n=Math.max(1,n-1);pd()};$('#pl').onclick=function(){n++;pd()}}pd()}
if(pg=='cart'){St.onCart=function(){var L=St.lines(),t=St.totals();
 $('#items').innerHTML=L.length?L.map(function(l){return '<div class="it"><div class="t" style="--t:'+l.p.tone+'"></div><div><h3>'+l.p.name+'</h3><div class="c">'+l.p.sub+'<br><button data-dec="'+l.p.id+'">-</button>'+l.q+'<button data-inc="'+l.p.id+'">+</button><button class="rm" data-rm="'+l.p.id+'">Remove</button></div></div><div>'+f(l.t)+'</div></div>'}).join(''):'<p style="border-top:1px solid #e6e4df;padding-top:22px">Your bag is empty. <a class="ul" href="shop.html">Continue shopping</a></p>';
 $('#sum').innerHTML='<h2>Summary</h2><div><span>Subtotal</span><span>'+f(t.sub)+'</span></div>'+(t.d?'<div><span>Discount</span><span>-'+f(t.d)+'</span></div>':'')+'<div><span>Shipping</span><span>'+(t.sh?f(t.sh):'Free')+'</span></div><div class="g"><span>Total</span><span>'+f(t.total)+'</span></div><div style="border:0;padding-top:20px"><input id="cc" placeholder="Coupon code"><button class="cp" id="ca">Apply</button></div><button class="bk" data-checkout '+(t.n?'':'disabled')+'>Checkout</button>';
 $('#ca').onclick=function(){if(St.coupon($('#cc').value))St.onCart();else St.toast('Invalid coupon')}}}
})();