(function(){var St=window.St,$=St.$,f=St.fmt,S=St.S,pg=document.body.dataset.page;
$('#pt').textContent=document.title.split('|')[0];
var hdr='<div class="r hdr"><span></span><span>Product</span><span class="sp">Specification</span><span style="text-align:right">Price</span><span>Qty</span><span></span></div>';
function row(p){return '<div class="r"><div class="th" style="--t:'+p.tone+'"></div><div><a class="n" href="product.html?id='+p.id+'">'+p.name+'</a><small>SKU SS-'+(2000+p.id)+'</small></div><span class="sp">'+p.sub+'</span><div><b>'+f(p.price)+'</b>'+(p.old?'<s>'+f(p.old)+'</s>':'')+'</div><input id="q'+p.id+'" type="number" min="1" value="1"><button class="bt" data-add="'+p.id+'" data-qin="#q'+p.id+'">Add</button></div>'}
St.onCart=function(){var t=St.totals();$('#ct').textContent=f(t.total-t.sh);
 if(pg!='cart')return;var L=St.lines();
 $('#items').innerHTML=L.length?'<div class="tbl"><div class="ci hdr"><span></span><span>Product</span><span>Price</span><span>Qty</span><span>Total</span><span></span></div>'+L.map(function(l){return '<div class="ci"><div class="th" style="width:44px;height:44px;background:'+l.p.tone+'"></div><div><a class="n" href="product.html?id='+l.p.id+'"><b>'+l.p.name+'</b></a><small>'+l.p.sub+'</small></div><span>'+f(l.p.price)+'</span><div class="q"><button data-dec="'+l.p.id+'">-</button><span>'+l.q+'</span><button data-inc="'+l.p.id+'">+</button></div><b>'+f(l.t)+'</b><button class="lk" data-rm="'+l.p.id+'">Remove</button></div>'}).join('')+'</div>':'<div class="bx">Your cart is empty. <a href="shop.html"><u>Go to products</u></a></div>';
 $('#sum').innerHTML='<div><span>Subtotal</span><span>'+f(t.sub)+'</span></div>'+(t.d?'<div><span>Discount</span><span>-'+f(t.d)+'</span></div>':'')+'<div><span>Shipping</span><span>'+(t.sh?f(t.sh):'Free')+'</span></div><div class="g"><span>Total</span><span>'+f(t.total)+'</span></div><p style="margin:10px 0 6px"><input id="cc" placeholder="Coupon: WELCOME10"> <button class="bt o" id="ca">Apply</button></p><button class="bt" style="width:100%" data-checkout '+(t.n?'':'disabled')+'>Place order</button>';
 $('#ca').onclick=function(){if(St.coupon($('#cc').value))St.onCart();else St.toast('Invalid coupon')}};
if(pg=='home')$('#feat').innerHTML=hdr+St.P.slice(0,6).map(row).join('');
if(pg=='shop'){var cat=St.qs('cat')||'All',q=(St.qs('q')||'').toLowerCase();function d(){var l=St.list({cat:cat,q:q});$('#tabs').innerHTML=['All'].concat(S.cats).map(function(c){return '<button class="'+(c==cat?'on':'')+'" data-c="'+c+'">'+c+'</button>'}).join('');$('#grid').innerHTML=hdr+(l.length?l.map(row).join(''):'<div class="r">No products found.</div>')}$('#tabs').onclick=function(e){if(e.target.dataset.c){cat=e.target.dataset.c;d()}};d()}
if(pg=='product'){var p=St.by(St.qs('id'))||St.P[0];document.title=p.name+' | '+S.name;$('#pt').textContent=p.name;
 $('#pdp').innerHTML='<div class="crumb"><a href="shop.html">Products</a> / '+p.cat+'</div><div class="pw"><div><div class="ph" style="--t:'+p.tone+'">Product photo</div><h1>'+p.name+'</h1><div class="crumb">SKU SS-'+(2000+p.id)+' &nbsp;|&nbsp; Rated '+p.rating+'/5</div><table class="sp2"><tr><td>Category</td><td>'+p.cat+'</td></tr><tr><td>Specification</td><td>'+p.sub+'</td></tr><tr><td>Rating</td><td>As per client datasheet</td></tr><tr><td>Warranty</td><td>1 year</td></tr></table><h3>Description</h3><p>'+p.name+'. Placeholder copy: replace with the client description and installation notes.</p></div><div class="buy"><div class="crumb">Price per unit, GST extra</div><div class="pr">'+f(p.price)+(p.old?'<s>'+f(p.old)+'</s>':'')+'</div><label>Quantity<input id="qn" type="number" min="1" value="1"></label><button class="bt" data-add="'+p.id+'" data-qin="#qn">Add to cart</button><a class="bt o" href="contact.html">Ask for bulk price</a><ul><li>Ships in 2 working days</li><li>GST invoice provided</li><li>Install help on call</li></ul></div></div>'}
})();